/**
 * HTTP, Auth, JWT, Text and Time constants
 * No process.env or parseIntEnv
 */

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_SERVER_ERROR: 500
};

const AUTH = {
  BEARER_PREFIX: 'Bearer ',
  TOKEN_START_INDEX: 7
};

const JWT = {
  ACCESS_TOKEN_EXPIRE: '15m',
  REFRESH_TOKEN_EXPIRE: '7d'
};

const TEXT_LIMITS = {
  MIN_MESSAGE_LENGTH: 1,
  MIN_ISSUE_DESCRIPTION_LENGTH: 10,
  MAX_MESSAGE_LENGTH: 5000,
  MAX_ISSUE_DESCRIPTION_LENGTH: 5000,
  MAX_RESOLUTION_LENGTH: 5000,
  MAX_REPLY_LENGTH: 5000
};

const TIME = {
  TEN_MINUTES_MS: 10 * 60 * 1000,
  FIFTEEN_MINUTES_MS: 15 * 60 * 1000,
  ONE_HOUR_MS: 60 * 60 * 1000,
  ONE_DAY_MS: 24 * 60 * 60 * 1000
};

module.exports = {
  HTTP_STATUS,
  AUTH,
  JWT,
  TEXT_LIMITS,
  TIME
};
